### ISSUE TITLE
Connect Spinetoolbox to a database server

### ISSUE THREAD

**Issue by daspartha** [spine-tools/Spine-Toolbox#2329]
Currently the data-connection tool in the Spinetoolbox provides connections to text, csv, excel files.

In the MOPO project we are trying to connect directly AidRES database (PostgreSQL) to Spinetoolbox by creating specific 'Views' so that we do not need to manage a lots of R scripts to create flat files in specific formats. 

Is it a good idea to develop the connections for PostgreSQL and also Microsoft SQL?

**Comment by manuelma** [comment]
Yes, it is an excellent idea and it should be possible with not too much effort.

**Comment by soininen** [comment]
It is possible to provide a general-purpose URL in Data connection that could connect to a PostgreSQL database. That is just a way to get the URL into Toolbox, though. What other functionality we may be missing to better support different databases?

**Comment by manuelma** [comment]
Postgre is disallowed at the moment, you cannot select it in the combobox. I'm not sure what we were thinking, probably it's just a mistake (because we don't support postgre in spinedb_api, but we should support it in Data Connection). So it's very easy but somebody probably needs to test it and check it works...

**Comment by soininen** [comment]
> Postgre is disallowed at the moment, you cannot select it in the combobox.

True, I should have checked it first. I can select postgresql from the URL dialog but it says that it cannot generate URL. mssql on the other hand gives a warning "Please create an SQL Server ODBC Data Source first".

**Comment by daspartha** [comment]
Is there any update to the Spinetoolbox planned regarding this issue in upcoming days?

**Comment by soininen** [comment]
I can have a look at this.

**Comment by soininen** [comment]
All the database dialects listed in the Select URL dialog should now work. However, the protocol field of the URL gets modified such that the URL works with SqlAlchemy and Importers/Exporters. If "raw" URLs are desired, we need to add another reference type to Data connection.

In any case, @daspartha could you please update Spine Toolbox and check if the postgresql works for you? I do not have access to PostgreSQL databases so I cannot test it.

The changes were backported from `0.8-dev` to `main`.

**Comment by daspartha** [comment]
Hi, sorry to reply late.
I am trying the connection now.
I have updated the Spinetoolbox and setup AidRES PSQL database.
AidRES database runs at localhost with port no. 5432.

When I am trying to establish connection from Spinetoolbox using URL in data connection tool I am facing a problem.
Even after filling up all necessary fields, the 'OK' button is greyed out and a message displayed below saying "Unable to generate URL from selections: 'postgresql'".

Could you please help me how can I establish the connection? 

![image](https://github.com/spine-tools/Spine-Toolbox/assets/11335572/859c942a-9003-4a35-a28a-5b98fed37dcd)

![image](https://github.com/spine-tools/Spine-Toolbox/assets/11335572/49ff93f5-6ffe-469a-83ee-721e50acce27)

**Comment by soininen** [comment]
This should have been fixed on `master` branch as well --- I don't recommend using `0.8-dev` branch since it's under heavy development and isn't really stable.

That being said, did you update Toolbox requirements as well? The command would be `python -mpip install --upgrade -r requirements.txt`

Do you see any error messages or Tracebacks in the terminal where you started Toolbox?

I just tried this out on my system and the Select URL dialog works without issues here.

**Comment by daspartha** [comment]
Thanks @soininen for you reply.
I removed all my previous installations and envs and created a fresh env and Spinetoolbox installation of the master branch.

I can see that the URL dialogue box works. But I am still facing problems. 
After updating all fields, Spinetoolbox still reports errors (please see the screenshot). It says no password supplied though I mentioned the password in the URL dialogue box.

![image](https://github.com/spine-tools/Spine-Toolbox/assets/11335572/539617b4-1536-4be3-ad38-8ffc75382d8f)

![image](https://github.com/spine-tools/Spine-Toolbox/assets/11335572/8885c4cc-d825-46bc-9e0f-a7e28fec7505)

**Comment by daspartha** [comment]
Hi @soininen,

I removed all the previous envs and spinetoolbox installations and created a fresh env and spinetoolbox installation of the master branch. 

It seems the connection to the database works but in the importer specification editor, I do not see any tables that are in the database. I am using SqlAlchemy connector. Therefore I do not know how to proceed. 
In the source data tab I see many columns with heading header_1, header_2 and values are like item_1_1. 

Could you please guide me how can I import specific tables from the PSQL database? 

![image](https://github.com/spine-tools/Spine-Toolbox/assets/11335572/c2eee5db-b394-401c-9ae9-02afe2dd38b4)

**Comment by soininen** [comment]
I got postgresql installed on my system and discovered a bunch of issues with it and Toolbox. I will try to get those fixed so hopefully Importer will show actual data from the database sometime soon.

Apologies for the issues! I do not think we have ever had anyone using a remote database as a data source before so much of the related functionality in Toolbox is untested.

**Comment by soininen** [comment]
The issues plaguing have now been fixed. Importer's Specification editor should now show the tables of the database properly once you select the SqlAlchemy connector. Importing the data seemed to work fine, too.

Next, I will fix the issues in the `0.8-dev` branch, too.

**Comment by daspartha** [comment]
Hi @soininen,

Thank you very much for taking time to solve the issue.
However this still doesn't work for me. 

I did a fresh spinetoolbox installation.
When I click on the data importer tool and select SqlAlchemy connector, the importer specification editor doesn't show any tables. For me the tables of AidRES database are under aidres Schema.

How does it look at your end?
If it working smoothly at your end, is it possible to do a short online meeting so that I can replicate the same?

Best,
Partha

![image](https://github.com/spine-tools/Spine-Toolbox/assets/11335572/d63fc0e0-ca4d-4adb-960b-369436c94282)

**Comment by soininen** [comment]
Importer is working smoothly on my end. Here is the Source data preview from a postgresql tutorial database:
![image](https://github.com/spine-tools/Spine-Toolbox/assets/19147159/1e0155ea-172e-4325-8aba-b5ae2d2f4439)

Importer is database schema agnostic. It just reads data from the tables as-is.

The Tracebacks on the command line need fixing (at least in the `0.8-dev` branch) but are not linked to the issue at hand.

We can do a support call. You can reach me over Element (click the 'chat on gitter' badge at the top of our [README](https://github.com/spine-tools/Spine-Toolbox#spine-toolbox)) where we can sort out the details.

**Comment by daspartha** [comment]
Hi @soininen I did a fresh installation using 'python -m pipx install spinetoolbox'. However I do not see the tables in the database still. For a database with only public schema I see the tables in spinetoolbox.

**Comment by daspartha** [comment]
Hi @soininen, It works now. Many thanks.
